### ISSUE TITLE
Add support for answer files

### ISSUE THREAD

**Issue by kayone** [appget/appget#31]
We are encountering this more and more, 

There are a bunch of installers that require an answer file when doing an unattended install. They are no longer satisfied with arguments alone. eg. MS Office, the Most recent update of JetBrains IDEs (https://www.jetbrains.com/help/rider/Install_and_set_up__product_.html#silent-install) and InstallShield based installers

Proposed Solutions:

- we manage and host the answer file side-by-side with the manifest file.
eg. 
```
/manifests/rider/rider.yaml
/manifests/rider/answer.config
```

- Update the manifest with a token signalling appget to download and replace the local path of the answer file.

```
id: rider
name: Rider
version: 183.5619.41
home: https://www.jetbrains.com/rider/
installMethod: NSIS
args:
  silent: SILENT={{gh:answer.config}}
installers:
- location: https://download.jetbrains.com/rider/JetBrains.Rider-2018.3.3.exe
  sha256: 94d76d7d9b92026493ef70a358888f211e9353a8be1e25e364fc21842160985b
```

### Pseudo Code:
- Load the manifest as usual
- Check the args object for `{{gh:*}}` token
- If found download the file based on the name provided from the same path as the manifest itself
- place the downloaded answer file by the downloaded installer file
- replace `{{gh:*}}` token with the full path of the downloaded file
